"""initial schema

Revision ID: 88191bf97c62
Revises: 
Create Date: 2026-09-03 13:29:38.116902

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88191bf97c62'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breakout_price', sa.Float(), nullable=False),
    sa.Column('breakout_volume', sa.Float(), nullable=True),
    sa.Column('breakout_volume_ratio', sa.Float(), nullable=True),
    sa.Column('average_daily_10days_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alert_events_detected_at'), 'stock_alert_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_stock_alert_events_symbol'), 'stock_alert_events', ['symbol'], unique=False)
    op.create_table('stock_daily_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_volume', sa.Float(), nullable=True),
    sa.Column('delivery_percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_daily_data_symbol'), 'stock_daily_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_daily_data_trading_date'), 'stock_daily_data', ['trading_date'], unique=False)
    op.create_table('stock_technical_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('all_time_high', sa.Float(), nullable=True),
    sa.Column('all_time_low', sa.Float(), nullable=True),
    sa.Column('distance_from_52w_high_pct', sa.Float(), nullable=True),
    sa.Column('distance_from_52w_low_pct', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_100', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_9', sa.Float(), nullable=True),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_100', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('distance_from_ema_20_pct', sa.Float(), nullable=True),
    sa.Column('distance_from_ema_50_pct', sa.Float(), nullable=True),
    sa.Column('distance_from_ema_200_pct', sa.Float(), nullable=True),
    sa.Column('change_1d_pct', sa.Float(), nullable=True),
    sa.Column('change_5d_pct', sa.Float(), nullable=True),
    sa.Column('change_10d_pct', sa.Float(), nullable=True),
    sa.Column('change_20d_pct', sa.Float(), nullable=True),
    sa.Column('change_50d_pct', sa.Float(), nullable=True),
    sa.Column('change_200d_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('average_volume_5d', sa.Float(), nullable=True),
    sa.Column('average_volume_10d', sa.Float(), nullable=True),
    sa.Column('average_volume_20d', sa.Float(), nullable=True),
    sa.Column('average_volume_50d', sa.Float(), nullable=True),
    sa.Column('volume_ratio_5d', sa.Float(), nullable=True),
    sa.Column('volume_ratio_10d', sa.Float(), nullable=True),
    sa.Column('volume_ratio_20d', sa.Float(), nullable=True),
    sa.Column('volume_ratio_50d', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_14_pct', sa.Float(), nullable=True),
    sa.Column('adx_14', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('stochastic_k', sa.Float(), nullable=True),
    sa.Column('stochastic_d', sa.Float(), nullable=True),
    sa.Column('price_above_ema_50', sa.Boolean(), nullable=True),
    sa.Column('price_above_ema_200', sa.Boolean(), nullable=True),
    sa.Column('golden_cross', sa.Boolean(), nullable=True),
    sa.Column('death_cross', sa.Boolean(), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_technical_snapshots_symbol'), 'stock_technical_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_technical_snapshots_trading_date'), 'stock_technical_snapshots', ['trading_date'], unique=False)
    op.create_table('stocks_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_master_symbol'), 'stocks_master', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_master_symbol'), table_name='stocks_master')
    op.drop_table('stocks_master')
    op.drop_index(op.f('ix_stock_technical_snapshots_trading_date'), table_name='stock_technical_snapshots')
    op.drop_index(op.f('ix_stock_technical_snapshots_symbol'), table_name='stock_technical_snapshots')
    op.drop_table('stock_technical_snapshots')
    op.drop_index(op.f('ix_stock_daily_data_trading_date'), table_name='stock_daily_data')
    op.drop_index(op.f('ix_stock_daily_data_symbol'), table_name='stock_daily_data')
    op.drop_table('stock_daily_data')
    op.drop_index(op.f('ix_stock_alert_events_symbol'), table_name='stock_alert_events')
    op.drop_index(op.f('ix_stock_alert_events_detected_at'), table_name='stock_alert_events')
    op.drop_table('stock_alert_events')
    # ### end Alembic commands ###
