"""add breakout_date to stock_alert_events

Revision ID: ac444a0f3818
Revises: 88191bf97c62
Create Date: 2026-09-03 14:45:56.631935

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac444a0f3818'
down_revision: str | None = '88191bf97c62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add nullable first, backfill existing rows from detected_at, then
    # tighten to NOT NULL — a straight NOT NULL add_column fails on any
    # table that already has rows.
    op.add_column('stock_alert_events', sa.Column('breakout_date', sa.Date(), nullable=True))
    op.execute("UPDATE stock_alert_events SET breakout_date = detected_at::date WHERE breakout_date IS NULL")
    op.alter_column('stock_alert_events', 'breakout_date', nullable=False)
    op.create_index(op.f('ix_stock_alert_events_breakout_date'), 'stock_alert_events', ['breakout_date'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_alert_events_breakout_date'), table_name='stock_alert_events')
    op.drop_column('stock_alert_events', 'breakout_date')
    # ### end Alembic commands ###
